# Califonia lotto number prediction project

In [1]:
import pandas as pd

data = pd.read_csv("num.csv", index_col='seq')

In [2]:
data

1   2   3   4   5   6  bonus
seq                                
1000   2   8  19  22  32  42     39
999    1   3   9  14  18  28     34
998   13  17  18  20  42  45     41
997    4   7  14  16  24  44     20
996    6  11  15  24  32  39     28
...   ..  ..  ..  ..  ..  ..    ...
5     16  24  29  40  41  42      3
4     14  27  30  31  40  42      2
3     11  16  19  21  27  31     30
2      9  13  21  25  32  42      2
1     10  23  29  33  37  40     16

[1000 rows x 7 columns]

In [3]:
import numpy as np

data = np.array(data)
X = data[:,:-1]
y = data[:,-1]

print("X.shape:", X.shape)
print("y.shape:", y.shape)

X.shape: (1000, 6)
y.shape: (1000,)


In [4]:
X = X.reshape(-1, 1, 6)
y = y.reshape(-1, 1)

print("X.shape:", X.shape)
print("y.shape:", y.shape)

X.shape: (1000, 1, 6)
y.shape: (1000, 1)


In [5]:
X[0]

array([[ 2,  8, 19, 22, 32, 42]], dtype=int64)

In [6]:
y[0]

array([39], dtype=int64)

### model creation

In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from tensorflow.keras.layers import Input

model = Sequential()
model.add(LSTM(64, input_shape=(1, 6), return_sequences=True))
model.add(Dense(128, activation='softmax'))
model.add(Dense(1, activation='softmax'))
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [8]:
model.fit(X, y)

Instructions for updating:
The `validate_indices` argument has no effect. Indices are always validated on CPU and never validated on GPU.
32/32 [==============================] - 3s 5ms/step - loss: nan - accuracy: 0.0290


In [9]:
test = np.array([list(X[7])])

pred = model.predict(test)
pred

array([[[1.]]], dtype=float32)